### ISSUE TITLE
Plausible input results in a System.FormatException

### ISSUE THREAD

**Issue by fivdi** [vplotnikow/FootballTeamGenerator#1]
After downloading and running FootballTeamGenerator everything worked correctly the first time I ran the program. Here is what I saw:
```
c:\src\FootballTeamGeneratorV1.0>FootballTeamGeneratorV1.0.exe
Willkommen zum Football Team Generator! Mit wie vielen Personen möchtest du spielen? (2 oder 4)
2
Okay, 2 Spieler also.

Gib nun bitte nacheinander die Spielernamen ein und bestätige nach jedem Namen mit Enter.

Spieler 1:
Harry
Spieler 2:
Joe

Team 1 (Joe) = Kolumbien
Team 2 (Harry) = Venezuela

Ich wünsche beiden Teams viel Erfolg und Gut Kick!

c:\src\FootballTeamGeneratorV1.0>
```
The second time I ran the program there was an unhandled  `System.FormatException`:
```
c:\src\FootballTeamGeneratorV1.0>FootballTeamGeneratorV1.0.exe
Möchten Sie die zuletzt eingegebene Spielernamen (Harry, Joe) verwenden? Antworten Sie mit ja oder nein.
n


Unbehandelte Ausnahme: System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean
parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei System.Convert.ToInt32(String value)
   bei FootballTeamGenerator.Player.Input(String[] konsolenParameter)
   bei FootballTeamGenerator.Program.Main(String[] args)

c:\src\FootballTeamGeneratorV1.0>
```
During the second run of the program I was asked the following question:
```
Möchten Sie die zuletzt eingegebene Spielernamen (Harry, Joe) verwenden? Antworten Sie mit ja oder nein.
```
Instead of answering "ja" or "nein" I answered "n" as this is what I am used to from using other programs so I expected it to work. Aftering answering "n" and hitting the "enter" key, nothing happened, so I hit the "enter" key again. This resulted in a `System.FormatException`.

It would be good if the program accepted "j" and "n" as valid abbreviations for "ja" and "nein" respectively. Alternatively, the input could be validated and if it's invalid, the user could be told that it's invalid.

**Comment by aharnos** [comment]
**Thanks for your feedback @fivdi!**

In release 2.0 you can already answer with "yes" or "no" respectively with "y" or "n" if you will be asked. If you enter another words or letters, which aren't allowed, the `System.FormatException` will be nevertheles showed. We work on it and in the next release this problem will not oncourrence.

If you notice something, please write us a new issue or commnt.

**Comment by fivdi** [comment]
> Thanks for your feedback @fivdi!

You're welcome @aharnos  😄

> In release 2.0 you can already answer with "yes" or "no" respectively with "y" or "n" if you will be asked.

Excellent, I just tried it and it worked, good job 👍 

The ASCII art on program startup is nice.
```
-----------------------------------------------------------------v2.0
                                                             ___
  o__                                                 o__   |   |\
 /|       Welcome To The Football Team Generator!     /\    |   |X\
 / > o                                                 <\   |   |XX\
---------------------------------------------------------------------
```

> If you notice something, please write us a new issue or commnt.

Will do.
